### ISSUE TITLE
Is it possible to chain multiple resolvers on the same query

### ISSUE THREAD

**Issue by youngpayters** [jurijzahn8019/aws-promise-jest-mock#430]
I'm looking to have something like this. The idea is that I have 2 query calls, 1 on a table and then another on an index. Would like to be able to have 2 results for the same mocked method.

```
const dynamoQueryMock = on(DocumentClient)
      .mock("query")
      .resolve({ Items: [{ id: "0f4a1175-476a-446b-b62c-41485ab5b668"}]})
      .resolve({ Items: [{ title: "Topic Name 123"});
```

**Comment by youngpayters** [comment]
I'm looking to have something like this. The idea is that I have 2 query calls, 1 on a table and then another on an index. Would like to be able to have 2 results for the same mocked method.

```
const dynamoQueryMock = on(DocumentClient)
      .mock("query")
      .resolve({ Items: [{ id: "0f4a1175-476a-446b-b62c-41485ab5b668"}]})
      .resolve({ Items: [{ title: "Topic Name 123"});
```

**Comment by jurijzahn8019** [comment]
Should be possible by utilize "*once" functions on Mock. I will look Into it.

**Comment by jurijzahn8019** [comment]
Released: <https://github.com/jurijzahn8019/aws-promise-jest-mock/releases/tag/v2.2.0>

**Comment by youngpayters** [comment]
This is a super handy library and thanks a million for the quick turnaround on this! Already pushing this handy library across the team now 😄

**Comment by jurijzahn8019** [comment]
Glad to hear that! Makes me really happy! 🤗
